[package]
name = "icaller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
http = "1.1.0"
reqwest = "0.11.25"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
